controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Post;
use app\models\Tag;
use app\models\TagAssign;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\Users;
use yii\web\UploadedFile;
use yii\data\Pagination;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $tags = Tag::find()->all();
        $query = Post::find()->where(['status' => 'active']);
        $count = $query->count();
        $pagination = new Pagination(['totalCount' => $count]);
        $posts = $query->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        $popularPosts = Post::find()->orderBy(['count_view' => SORT_DESC])->all();
        $newPosts = Post::find()->orderBy(['created_at' => SORT_DESC])->all();
        return $this->render('index',['posts' => $posts, 'tags' => $tags, 'popularPosts' => $popularPosts,'newPosts' => $newPosts, 'pagination' => $pagination]);
    }

    public function actionSignup()
    {
        if(!Yii::$app->user->isGuest)
            return $this->goHome();

        $model = new Users();

        if($model->load(Yii::$app->request->post())){
            $model->setPassword($model->password);
            $model->generateAuthKey();
            $model->status = 'active';
            $model->role = 'user';
            $model->created_at = date('Y-m-d H:m:s');
            $model->file = UploadedFile::getInstance($model,'file');
            if(!empty($model->file))
            {
                $imageName = $model->fullname;
                $model->file->saveAs('uploads/users/'.$imageName.'.'.$model->file->extension);
                $model->image = 'uploads/users/'.$imageName.'.'.$model->file->extension;
//                echo '<pre>';
//                print_r($model);
//                die();
            }
            if($model->validate())
            {
                $model->save();
                Yii::$app->session->setFlash('success', "You have signed up successfully. Pleace login.");
                return $this->redirect(['site/login']);
            }
        }
        $model->password='';
        return $this->render('signup',[
            'model'=>$model,
        ]);
    }
    public function actionTag($id)
    {
        $assigns = TagAssign::find()->where(['tag_id' => $id])->all();
        $posts = [];
        foreach ($assigns as $assign)
        {
            $post = Post::findOne($assign->post_id);
            $posts[]= $post;
        }
//        echo '<pre>';
//        print_r($posts);
//        die();
        return $this->render('tag',['posts' => $posts]);
    }
    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }


        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }
    public function actionCategory($id)
    {
        $posts = Post::find()->where(['category_id' => $id])->all();
        return $this->render('category',['posts' => $posts]);
    }
    public function actionPost($id)
    {
        $tag_assaign = TagAssign::find()->where(['post_id' => $id])->all();
        $post = Post::findOne($id);
        $post->count_view++;
        $post->save();
        return $this->render('post',['post' => $post, 'tags' => $tag_assaign]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/category.php
<!-- Post -->
<section class="bg0 p-t-70 p-b-55">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 p-b-80">
                <div class="row">
                    <?php foreach ($posts as $post):?>
                    <div class="col-sm-6 p-r-25 p-r-15-sr991">
                        <!-- Item latest -->
                        <div class="m-b-45">
                            <a href="/site/post?id=<?= $post->id?>" class="wrap-pic-w hov1 trans-03">
                                <img src="/<?= $post->image?>" alt="IMG">
                            </a>
                            <div class="p-t-16">
                                <h5 class="p-b-5">
                                    <a href="/site/post?id=<?= $post->id?>" class="f1-m-3 cl2 hov-cl10 trans-03">
                                        <?= $post->title?>
                                    </a>
                                </h5>

                                <span class="cl8">
										<a href="#" class="f1-s-4 cl8 hov-cl10 trans-03">
											avtor <?= $post->user->fullname?>
										</a>

										<span class="f1-s-3 m-rl-3">
											-
										</span>

										<span class="f1-s-3">
											<?= $post->created_at?>
										</span>
									</span>
                            </div>
                        </div>
                    </div>
                    <?php endforeach;?>
                </div>
            </div>
        </div>
    </div>
</section>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
use yii\widgets\LinkPager;
use yii\helpers\Html;
$this->title = 'Bosh sahifa';
?>
<!-- Post -->
<section class="bg0 p-t-70 p-b-55">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 p-b-80">
                <div class="row">
                    <?php foreach ($posts as $post):?>
                    <div class="col-sm-6 p-r-25 p-r-15-sr991">
                        <!-- Item latest -->
                        <div class="m-b-45">
                            <a href="/site/post?id=<?= $post->id?>" class="wrap-pic-w hov1 trans-03">
                                <img src="/<?= $post->image?>" alt="IMG" height="300">
                            </a>
<!--                            --><?//= \yii\helpers\Html::a('<img src="$post->image" alt="IMG" height="300">',['post'],['class' => 'wrap-pic-w hov1 trans-03'])?>
                            <div class="p-t-16">
                                <h5 class="p-b-5">
                                    <a href="/site/post?id=<?= $post->id?>" class="f1-m-3 cl2 hov-cl10 trans-03">
                                        <?= $post->title?>
                                    </a>
                                </h5>
                                <h6>Ko'rilgan: <?= $post->count_view?></h6>
                                <span class="cl8">
										<a href="#" class="f1-s-4 cl8 hov-cl10 trans-03">
											avtor <?=$post->user->fullname?>
										</a>

										<span class="f1-s-3 m-rl-3">
											-
										</span>

										<span class="f1-s-3">
											<?=$post->created_at?>
										</span>
									</span>
                            </div>
                        </div>
                    </div>
                    <?php endforeach;?>
                </div>

                <!-- Pagination -->
                <div class="flex-wr-s-c m-rl--7 p-t-15">
                    <?= LinkPager::widget([
                        'pagination' => $pagination,
                    ]);?>
                </div>
            </div>

            <div class="col-md-10 col-lg-4 p-b-80">
                <div class="p-l-10 p-rl-0-sr991">
                    <!-- Most Popular -->
                    <div class="p-b-23">
                        <div class="how2 how2-cl4 flex-s-c">
                            <h3 class="f1-m-2 cl3 tab01-title">
                                Eng ko'p o'qilganlar
                            </h3>
                        </div>

                        <ul class="p-t-35">
                            <?php $id=1;?>
                            <?php foreach ($popularPosts as $one): ?>
                            <li class="flex-wr-sb-s p-b-22">
                                <div class="size-a-8 flex-c-c borad-3 size-a-8 bg9 f1-m-4 cl0 m-b-6">
                                    <?= $id++?>
                                </div>
                                <?= \yii\helpers\Html::a($one->title,['post', 'id' => $one->id],['class' => 'size-w-3 f1-s-7 cl3 hov-cl10 trans-03'])?>
                            </li>
                            <?php endforeach;?>
                        </ul>
                    </div>

                    <!-- Tag -->
                    <div>
                        <div class="how2 how2-cl4 flex-s-c m-b-30">
                            <h3 class="f1-m-2 cl3 tab01-title">
                                Teglar
                            </h3>
                        </div>

                        <div class="flex-wr-s-s m-rl--5">
                            <?php foreach ($tags as $tag): ?>
                            <?= Html::a($tag->name,['site/tag', 'id' => $tag->id],['class' => 'flex-c-c size-h-2 bo-1-rad-20 bocl12 f1-s-1 cl8 hov-btn2 trans-03 p-rl-20 p-tb-5 m-all-5'])?>
                            <?php endforeach;?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- Latest -->
<section class="bg0 p-t-60 p-b-35">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 p-b-20">
                <div class="how2 how2-cl4 flex-s-c m-r-10 m-r-0-sr991">
                    <h3 class="f1-m-2 cl3 tab01-title">
                        So'ngi habarlar
                    </h3>
                </div>

                <div class="row p-t-35">
                    <?php foreach ($newPosts as $post): ?>
                    <div class="col-sm-6 p-r-25 p-r-15-sr991">
                        <!-- Item latest -->
                        <div class="m-b-45">
                            <a href="site/post?id=<?= $post->id?>" class="wrap-pic-w hov1 trans-03">
                                <img src="/<?=$post->image?>" alt="IMG" width="200" height="250">
                            </a>

                            <div class="p-t-16">
                                <h5 class="p-b-5">
                                    <a href="site/post?id=<?= $post->id?>" class="f1-m-3 cl2 hov-cl10 trans-03">
                                        <?= $post->title?>
                                        <p class="text-success">Ko'rilganlar: <?= $post->count_view?></p>
                                    </a>
                                </h5>

                                <span class="cl8">
										<a href="#" class="f1-s-4 cl8 hov-cl10 trans-03">
											avtor <?= $post->user->fullname?>
										</a>

										<span class="f1-s-3 m-rl-3">
											-
										</span>

										<span class="f1-s-3">
											<?= $post->created_at?>
										</span>
									</span>
                            </div>
                        </div>
                    </div>
                    <?php endforeach;?>
                </div>
            </div>
        </div>
    </div>
</section>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <div class="center-block">
    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
    </div>
</div>

views/site/post.php
<?php
use yii\helpers\Html;
?>
<!-- Content -->
<section class="bg0 p-b-70 p-t-5">
    <!-- Title -->
    <div class="bg-img1 size-a-18 how-overlay1" style="background-image: url('/<?=$post->image?>');">
        <div class="container h-full flex-col-e-c p-b-58">
            <?= Html::a($post->title, ['site/post', 'id' => $post->id],['class' => 'f1-s-10 cl0 hov-cl10 trans-03 text-uppercase txt-center m-b-33'])?>
            <h3 class="f1-l-5 cl0 p-b-16 txt-center respon2">
                <?= $post->description?>
            </h3>

            <div class="flex-wr-c-s">
					<span class="f1-s-3 cl8 m-rl-7 txt-center">
						<a href="#" class="f1-s-4 cl8 hov-cl10 trans-03">
							avtor <?= $post->user->fullname?>
						</a>

						<span class="m-rl-3">-</span>

						<span>
							<?= $post->created_at?>
						</span>
					</span>

                <span class="f1-s-3 cl8 m-rl-7 txt-center">
						<?= $post->count_view ?> Views
					</span>
            </div>
        </div>
    </div>

    <!-- Detail -->
    <div class="container p-t-82">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 p-b-100">
                <div class="p-r-10 p-r-0-sr991">
                    <!-- Blog Detail -->
                    <div class="p-b-70">
                        <p class="f1-s-11 cl6 p-b-25">
                            <?= $post->content?>
                        </p>
                        <!-- Tag -->
                        <div class="flex-s-s p-t-12 p-b-15">
								<span class="f1-s-12 cl5 m-r-8">
									Teglar:
								</span>

                            <div class="flex-wr-s-s size-w-0">
                                <?php foreach ($tags as $tag):?>
                                <a href="#" class="f1-s-12 cl8 hov-link1 m-r-15">
                                   <?= $tag->tag->name?>
                                </a>
                                <?php endforeach;?>
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
</section>

views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use  yii\helpers\ArrayHelper;
$this->title = 'Ro\'yxatdan o\'tish';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1 class="h1"><?= Html::encode($this->title) ?></h1>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>
    <?= $form->field($model,'fullname')->textInput()?>

    <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

    <?= $form->field($model, 'password')->passwordInput() ?>

    <?= $form->field($model,'file')->fileInput()?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?= Html::submitButton('Register', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>
    <!---->
    <!--    <div class="col-lg-offset-1" style="color:#999;">-->
    <!--        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>-->
    <!--        To modify the username/password, please check out the code <code>app\models\User::$users</code>.-->
    <!--    </div>-->
</div>

views/site/tag.php
<!-- Post -->
<section class="bg0 p-t-70 p-b-55">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10 col-lg-8 p-b-80">
                <div class="row">
                    <?php foreach ($posts as $post):?>
                        <div class="col-sm-6 p-r-25 p-r-15-sr991">
                            <!-- Item latest -->
                            <div class="m-b-45">
                                <a href="/site/post?id=<?= $post['id']?>" class="wrap-pic-w hov1 trans-03">
                                    <img src="/<?= $post['image']?>" alt="IMG">
                                </a>

                                <div class="p-t-16">
                                    <h5 class="p-b-5">
                                        <a href="/site/post?id=<?= $post['id']?>" class="f1-m-3 cl2 hov-cl10 trans-03">
                                            <?= $post['title']?>
                                        </a>
                                    </h5>

                                    <span class="cl8">
										<a href="#" class="f1-s-4 cl8 hov-cl10 trans-03">
											avtor <?= $post['user']['fullname']?>
										</a>

										<span class="f1-s-3 m-rl-3">
											-
										</span>

										<span class="f1-s-3">
											<?= $post['created_at']?>
										</span>
									</span>
                                </div>
                            </div>
                        </div>
                    <?php endforeach;?>
                </div>
            </div>
        </div>
    </div>
</section>